# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish on npm & host on gh-pages on merge

on:
  # release:
  #   types: [published]
  push:
    branches:
      - npm-deployment

jobs:
  # Publish to npm

  # publish:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: '14'
  #         registry-url: 'https://registry.npmjs.org'

  #     - name: Reconfigure git to use HTTP authentication
  #       run: >
  #         git config --global url."https://github.com/".insteadOf
  #         ssh://git@github.com/
  #     - run: npm ci
  #     - run: npm test
  #     - run: npm run build
  #     - run: npm publish
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

  # Deploy example on gh pages
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/
      
      - name: Install and build react-volume-viewer
        run: npm ci && npm run build

      # - name: Install example
      #   run: npm install
      #   working-directory: "./example"
      # - name: Build example
      #   run: npm run build
      #   working-directory: "./example"

      - run: npm run predeploy

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: example/build